
name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true
      versionCode:
        description: 'Version number (50500)'
        required: true
        
jobs:
  createrelease:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Create pull request 
        uses: peter-evans/create-pull-request@v3.8.2
        with:
          branch: release/v${{github.event.inputs.versionName}}
          base: main
          token: ${{ secrets.GITHUB_TOKEN }}
